services:
  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.runCommand({ ping: 1 }).ok\" | grep 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - aevo_mongodb:/data/db

  mongodb-test:
    image: mongo:8
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.runCommand({ ping: 1 }).ok\" | grep 1"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  aevo_mongodb:
